location = /scpcbmap {
	return 301 /scpcbmap/;
}

location /scpcbmap/ {
	index index.html;
	alias /path/to/repo/scpcbUtility/frontend/;

	location /scpcbmap/api/ {
		proxy_pass http://localhost:1499/api/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}
}